services:
  postgres:
    image: postgres:latest
    container_name: course-advisor-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/schema/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data: